Add new page Resetpassword.tsx
revaturelabs/cep-frontend pull request #64
Opened 2020-08-04 20:32 UTC by fenglin9686

add new page call ResetPassword.tsx for reset user password in login folder, haven't connected to backend yet

2020-08-04 22:58 UTC, AnthonyNGarcia requested changes

2020-08-04 22:58 UTC, AnthonyNGarcia commented on src/Components/App.tsx
> +        <Route path="/" component={ResetPassword} exact />
Let's not override the "/" path. Make a new route, maybe called "/reset" or something. Right now it looks like the application will no longer show the login page.

2020-08-04 23:02 UTC, AnthonyNGarcia submitted a review, later dismissed

2020-08-05 05:05 UTC, AnthonyNGarcia approved these changes

2020-08-05 15:04 UTC, kdgreen398 requested changes
In ResetPassword.txt, the TextFields and Button should be wrapped inside of a Form tag

2020-08-05 16:22 UTC, kdgreen398 approved these changes

2020-08-05 16:22 UTC, merged