Conditional rendering
revaturelabs/cep-frontend pull request #65
Opened 2020-08-05 18:19 UTC by kdgreen398

2020-08-05 20:12 UTC, AnthonyNGarcia requested changes

2020-08-05 20:12 UTC, AnthonyNGarcia commented on src/Components/Common/Drawer/Drawer.tsx
> +    {
Use enums with the two values as ROLE_ADMIN and ROLE_CLIENT, instead of using "ADMIN" as a String

2020-08-05 21:00 UTC, smgruver approved these changes
All checked on my local machine!

2020-08-06 15:47 UTC, AnthonyNGarcia approved these changes

2020-08-06 15:49 UTC, merged